import { Entity, PrimaryColumn, Column, CreateDateColumn, UpdateDateColumn, Generated } from 'typeorm';

/**
 * ============================================================================
 * ENTITY TEMPLATE - Start Here When Creating a New Database Model
 * ============================================================================
 * 
 * This file is a TEMPLATE for creating TypeORM entities (database tables).
 * 
 * WHAT IS THIS FILE?
 * - A boilerplate/example showing the correct structure for database entities
 * - Entities map to database tables via TypeORM
 * - Each entity class = one database table
 * 
 * HOW TO USE THIS TEMPLATE:
 * 1. Copy this file: cp src/entities/Template.ts src/entities/YourEntity.ts
 * 2. Replace class name: TemplateItem → YourEntity
 * 3. Replace table name: template_items → your_table_name
 * 4. Add your columns with @Column() decorators
 * 5. Register in src/config/database.ts
 * 
 * EXAMPLE - Creating a User Entity:
 * 
 *   @Entity('users')
 *   export class User {
 *     @PrimaryColumn('uuid')
 *     @Generated('uuid')
 *     id: string;
 * 
 *     @Column('varchar')
 *     email: string;
 * 
 *     @Column('varchar')
 *     firstName: string;
 * 
 *     @Column('varchar')
 *     lastName: string;
 * 
 *     @Column('boolean', { default: true })
 *     isActive: boolean;
 * 
 *     @Column('json', { nullable: true })
 *     metadata: Record<string, any>;
 * 
 *     @CreateDateColumn()
 *     createdAt: Date;
 * 
 *     @UpdateDateColumn()
 *     updatedAt: Date;
 *   }
 * 
 * THEN REGISTER IT:
 * - Add to src/config/database.ts entities array
 * - Import: import { User } from '../entities/User';
 * - Update: const entities = [TemplateItem, User];
 * 
 * COMMON COLUMN TYPES:
 * - 'uuid'      : UUID primary key
 * - 'varchar'   : String (limited length)
 * - 'text'      : Long text
 * - 'integer'   : Whole numbers
 * - 'decimal'   : Fixed-point decimals
 * - 'boolean'   : true/false
 * - 'timestamp' : Date with time
 * - 'json'      : JSON data
 * 
 * KEY DECORATORS:
 * - @PrimaryColumn()      : Primary key (unique ID)
 * - @Generated()          : Auto-generated by database
 * - @Column()             : Regular column
 * - @CreateDateColumn()   : Auto-set on creation
 * - @UpdateDateColumn()   : Auto-updated on change
 * - @ManyToOne()          : Foreign key relationships
 * - @OneToMany()          : Reverse relationships
 * 
 * ============================================================================
 */

@Entity('template_items')
export class TemplateItem {
  // Auto-generated UUID primary key (PostgreSQL generates this)
  @PrimaryColumn('uuid')
  @Generated('uuid')
  id!: string;

  // Simple string column
  @Column('varchar')
  name!: string;

  // Optional text column (nullable: true = can be null)
  @Column('text', { nullable: true })
  description?: string;

  // Automatically set when record created
  @CreateDateColumn()
  createdAt!: Date;

  // Automatically updated when record changes
  @UpdateDateColumn()
  updatedAt!: Date;
}
